# Generated by Django 3.2.7 on 2021-12-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_list_private',
        ),
    ]
