# Generated by Django 3.2.9 on 2021-12-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_remove_userprofile_is_list_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdate',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.book'),
        ),
    ]
